name: Ruby Release

on:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7.3, 2.6.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Set up Git user
        run: |
          git config --global user.email "customer-engineering@urbanairship.com"
          git config --global user.name "customer-engineering"
      - name: Publish to RubyGems
        uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          GUTHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RELEASE_COMMAND: rake release
